#!/usr/bin/env python3
"""Expand the bundled camera Xacros to reusable URDFs (requires ROS xacro)."""
from pathlib import Path
import re
import shutil
import tempfile
import xml.etree.ElementTree as ET

import xacro

ROOT = Path(__file__).resolve().parents[1]
PACKAGES = ("rebot_visual_grasp", "realsense2_description", "orbbec_description", "uvc32_description")
MESH_PATHS = {
    "rebot_visual_grasp/description/meshes/": "mounts/",
    "realsense2_description/meshes/": "realsense/",
    "orbbec_description/meshes/gemini2/": "gemini2/",
    "uvc32_description/meshes/mounts/": "mounts/",
    "uvc32_description/meshes/uvc32/": "uvc32/",
}


def build():
    (ROOT / "urdf").mkdir(exist_ok=True)
    with tempfile.TemporaryDirectory() as directory:
        staging = Path(directory)
        shutil.copytree(ROOT / "source", staging, dirs_exist_ok=True)
        for path in staging.rglob("*.xacro"):
            text = path.read_text()
            # Keep the arm supplied by the simulator; this URDF is its fixed
            # wrist attachment, rooted at an empty gripper_end link.
            text = re.sub(r'<xacro:include[^>]+\$\(find rebotarm_bringup\)[^>]+/>',
                          '<link name="gripper_end"/>', text)
            for package in PACKAGES:
                text = text.replace(f"$(find {package})", str(staging / package))
            path.write_text(text)

        for model in ("d405", "d435i", "gemini2", "uvc32"):
            package = "uvc32_description/urdf" if model == "uvc32" else "rebot_visual_grasp/description/urdf"
            path = staging / package / f"rebotarm_rs_with_{model}.urdf.xacro"
            document = xacro.process_file(str(path))
            # Vendor macros provide the body, screw frame and optical frames;
            # assembly origins above are preserved verbatim from the source.
            xml = document.toxml()
            for prefix, destination in MESH_PATHS.items():
                xml = xml.replace(f"package://{prefix}", f"../meshes/{destination}")
            root = ET.fromstring(xml)
            root.set("name", f"rebot_wrist_{model}")
            ET.indent(root, space="  ")
            output = ROOT / "urdf" / f"{model}.urdf"
            output.write_text('<?xml version="1.0"?>\n<!-- Generated by scripts/build-wrist-camera-urdfs.py; see ../README.md. -->\n'
                              + ET.tostring(root, encoding="unicode") + "\n")
            print(output.relative_to(ROOT.parent))


if __name__ == "__main__":
    build()
